[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/mward95/deep_learning_challenge/blob/main/Optomized_Deep_learning(3).ipynb)

## Preprocessing

In [1]:
# Take url from github so that when others run the code the do not need to import the csv
url = 'https://raw.githubusercontent.com/mward95/deep_learning_challenge/main/Resources/charity_data.csv'

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
# application_df = pd.read_csv("charity_data.csv")
application_df = pd.read_csv(url)
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ['EIN','NAME', 'ASK_AMT' ])

In [4]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
IS_SUCCESSFUL 2

In [5]:
application_df.nunique()

APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
STATUS                     2
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
IS_SUCCESSFUL              2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(counts[counts<500].index)
application_types_to_replace
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
countsbinning = application_df['CLASSIFICATION'].value_counts()
countsbinning

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
countsclassification = countsbinning[countsbinning>1]
countsclassification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list (countsbinning[countsbinning<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [13]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df['IS_SUCCESSFUL'].values
X = application_df.drop('IS_SUCCESSFUL', axis=1).values


# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [23]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
num_features = len(X_train_scaled[0])
hidden_nodes_1 = 80
hidden_nodes_2 = 30
hidden_nodes_3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_1, input_dim=num_features, activation='relu'))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_2, activation='relu'))
nn.add(tf.keras.layers.Dense(units=hidden_nodes_3, activation='relu'))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 80)                3920

 dense_10 (Dense)            (None, 30)                2430

 dense_11 (Dense)            (None, 10)                310

 dense_12 (Dense)            (None, 1)                 11

=================================================================
Total params: 6,671
Trainable params: 6,671
Non-trainable params: 0
_________________________________________________________________

In [24]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5716 - accuracy: 0.7184
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7297
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7297
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7310
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7322
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7318
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7329
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7339
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7348
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5429 - accuracy: 0.7338
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7350
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7348
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7367
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7353
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7362
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7359
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7373
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7355
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7373
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7380
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7371
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7376
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7370
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7368
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7374
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7385
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7375
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7369
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7373
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7380
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7395
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7375
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7372
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7392
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7388
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7380
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7385
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7385
Epoch 41/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5352 - accuracy: 0.7381
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7385
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7374
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7395
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7395
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7379
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7389
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7383
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7384
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7393
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7388
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7385
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7382
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7396
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7387
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7383
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7401
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7400
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7399
Epoch 60/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5333 - accuracy: 0.7397
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7396
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7401
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7396
Epoch 64/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5330 - accuracy: 0.7394
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5329 - accuracy: 0.7407
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7399
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7393
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7406
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7389
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7396
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7390
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7392
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7394
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7404
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7397
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7407
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7400
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7403
Epoch 80/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.7397
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7401
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7408
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7405
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7403
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7399
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7404
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7402
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7407
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7392
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7420
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7394
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7400
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7405
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7406
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7400
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7395
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7397
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7401
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7399
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7406

In [26]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5572 - accuracy: 0.7279 - 456ms/epoch - 2ms/step
Loss: 0.5571571588516235, Accuracy: 0.7279300093650818

In [27]:
# Export our model to HDF5 file Save and export your results to an HDF5 file. Name the file AlphabetSoupCharity.h5
#  YOUR CODE GOES HERE
from google.colab import files

nn.save('/content/AlphabetSoupCharity_Optimzation(3).h5')
files.download('/content/AlphabetSoupCharity_Optimzation(3).h5')